In [16]:
import pandas as pd
data=pd.DataFrame({
    "name":['anu','ammu','anu','binnu'],
    "age":[18,17,18,79]}) 
print(data.duplicated())

0    False
1    False
2     True
3    False
dtype: bool

In [21]:
import pandas as pd
dataset={
    "Name":["noah","jonas","martha","luke"],
     "Age":[43,45,67,33]
}
result=pd.DataFrame(dataset)
print(result)

     Name  Age
0    noah   43
1   jonas   45
2  martha   67
3    luke   33

In [23]:
import pandas as pd
dataset={
    "Name":["noah","jonas","martha","luke"],
     "Age":[43,45,67,33]
}
result=pd.DataFrame(dataset)
print(result.duplicated())

0    False
1    False
2    False
3    False
dtype: bool

In [26]:
import pandas as pd
dataset={
    "Name":["noah","jonas","martha","noah"],
     "Age":[43,45,67,43]
}
result=pd.DataFrame(dataset)
print(result.drop_duplicates())

     Name  Age
0    noah   43
1   jonas   45
2  martha   67

In [28]:
employee={
    "Name":["ashmitha","akshaya","dhruvitha","ananya","mokshitha"],
    "salary":[34000,78000,67000,72000,64000]
}
result=pd.DataFrame(employee)
print(result)

        Name  salary
0   ashmitha   34000
1    akshaya   78000
2  dhruvitha   67000
3     ananya   72000
4  mokshitha   64000

In [32]:
employee={
    "Name":["ashmitha","akshaya","dhruvitha","ananya","mokshitha"],
    "salary":[34000,78000,67000,72000,64000]
}
result=pd.DataFrame(employee)
print(result[result["salary"]>50000])

        Name  salary
1    akshaya   78000
2  dhruvitha   67000
3     ananya   72000
4  mokshitha   64000

In [33]:
print(result.query("salary>30000"))

        Name  salary
0   ashmitha   34000
1    akshaya   78000
2  dhruvitha   67000
3     ananya   72000
4  mokshitha   64000

In [34]:
print(result.query("salary>30000 and salary<50000"))

       Name  salary
0  ashmitha   34000

In [35]:
favfruits={
    "fruits":["mango","jamun","strawberry","litchi"]
}
result=pd.DataFrame(favfruits)
print(result)

       fruits
0       mango
1       jamun
2  strawberry
3      litchi

In [39]:
(result.sample())

  fruits
1  jamun

In [40]:
(result.sample(3))

   fruits
3  litchi
0   mango
1   jamun

In [46]:
(result.sample(3,random_state=0))

       fruits
2  strawberry
3      litchi
1       jamun